store-url: http://RCThemePark.com/

blocks:
  yesBlock:
    name: "&a&lContinue..."
        
  buyBlock:
    name: "&f&oBuy FastPasses"
    
  noBlock:
    name: "&c&lCancel..."
      
attractions:
  BigThunderMountain:
     x: 1
     y: 1
     z: 1
     pitch: 1
     yaw: 1