name: FastPass
main: me.aberdeener.fastpass.FastPass
version: 0.4.9
authors: [Aberdeener, RoboticsMilan]
description: Add FastPass compatibility to the RCThemePark server.
website: http://RCThemePark.com
api-version: 1.13
commands:
   fastpass:
      usage: /fastpass <teleport|store|reload>
      description: Main command.